name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'release'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller app.py --onefile

      - name: Generate version
        run: echo "VERSION=2.0.$((github.run_number - 1))" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag v$VERSION
          git push origin v$VERSION

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: dist/*